# Generated by Django 5.1.4 on 2024-12-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kategoriler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=155)),
                ('aktifmi', models.BooleanField(default=True)),
            ],
        ),
    ]
