# Generated by Django 5.1.4 on 2024-12-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0005_markalar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markalar',
            options={'verbose_name': 'Marka', 'verbose_name_plural': 'Markalar'},
        ),
    ]
